### ISSUE TITLE
"issueベースの開発

### ISSUE THREAD

**Issue by maki1125** [maki1125/RUNTEQ_Graduate#28]
### 概要
動物を揃えるビンゴアプリ
ビンゴした動物をコレクションできる

### 実装予定の機能
- [ ]  ユーザー登録機能
- [ ]  ログイン機能
- [ ]  lineログイン機能
- [ ]  googleログイン機能
- [ ]  パスワードリセット機能
- [ ]  ビンゴ機能
- [ ]  コレクション機能
- [ ]  モード選択機能
- [ ]  お問い合わせ機能

### 必要なページ
- [ ]  トップページ
- [ ]  ユーザー登録ページ
- [ ]  ログインページ
- [ ]  パスワードリセット依頼ページ
- [ ]  パスワードリセットページ
- [ ]  ビンゴプレイページ（一人用）
- [ ]  ビンゴプレイページ（二人用）
- [ ]  コレクション一覧ページ
- [ ]  コレクション詳細ページ
- [ ]  モード選択ページ
- [ ]  お問い合わせページ
- [ ]  利用規約ページ
- [ ]  プライバシーポリシーページ

### Projectsのurl
https://github.com/users/maki1125/projects/2

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです！
